buku/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.buku_view, name='library'),
]

twitterlite/urls.py
from django.contrib import admin
from django.urls import path, include
from status import views as status_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', status_views.UpdateStatus, name='landing-page'),
    path('profile/', status_views.Profile, name='profile-page'),
    path("library/", include("buku.urls")),
    path("user/", include("users.urls")),
]

users/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "users"

urlpatterns = [
    path("register/", views.registration_view, name='register'),
    path("logout/", views.logout_view, name='logout'),
    path("login/", views.login_view, name='login')
]

status/models.py
from django.db import models

class Status(models.Model):
    message = models.TextField(max_length=300)
    date_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} {}".format(self.date_time, self.message)

templates/base.html
{% load static %}
{% load sean %}
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %} - TwitterLite</title>

    <link href="https://fonts.googleapis.com/css?family=Fredoka+One&display=swap" rel="stylesheet">
        <!-- font-family: 'Fredoka One', cursive; -->

    <!-- <link rel="stylesheet" href="{% static 'css/bootstrap/bootstrap.css' %}"> -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="{% static 'js/my-js.js' %}"></script>

    <nav id="navbar" class="navbar navbar-expand-md navbar-light border-bottom justify-content-between" style="background-color: rgb(0, 0, 12);">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand text-white" href="/">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            Gibah Online
        </a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- <div class="navbar-nav"> -->
            <div class="navbar-nav">
                <a class="nav-item nav-link mt-1" href="{% url 'profile-page' %}" style="font-weight: 400; color: white">Sean's Profile</a>                    
            </div>
            <div class="navbar-nav">
                <a class="nav-item nav-link mt-1" href="{% url 'library' %}" style="font-weight: 400; color: white">Library</a>                    
            </div>
            <label class="switch nav-item nav-link mt-2 ml-1">
                <input type="checkbox" checked>
                <span class="slider round"></span>
            </label>            
        </div>
        <div class="navbar-nav">
            <a class="nav-item nav-link mt-1" href="" style="font-weight: 400; color: white"> 
                Hello, 
                {% if request.user.is_authenticated %}
                    {{ request.session|get_item:request.user.username }}
                {% else %}
                    Guest
                {% endif %}
            </a>                    
        </div>
        {% if request.user.is_authenticated %}
        <div class="navbar-nav">
            <a class="nav-item nav-link mt-1" href="{% url 'users:logout' %}" style="font-weight: 400; color: white">Logout</a>                    
        </div>
        {% else %}
        <div class="navbar-nav">
            <a class="nav-item nav-link mt-1" href="{% url 'users:login' %}" style="font-weight: 400; color: white">Sign In</a>                    
        </div>
        <div class="navbar-nav">
            <a class="nav-item nav-link mt-1" href="{% url 'users:register' %}" style="font-weight: 400; color: white">Sign Up</a>                    
        </div>
        {% endif %}
    </nav>
          
</head>
<body>
    {% block content %}
    {% endblock %}    
</body>
    {% block script %}
    {% endblock %}
    <script>
        $("#id_message").attr("placeholder", '{{ PLACEHOLDER|safe }}');
    </script>
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</html>